# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.6.0"

[[constraint]]
  name = "github.com/graphql-go/graphql"
  version = "0.7.7"

[[constraint]]
  name = "github.com/graphql-go/handler"
  version = "0.2.2"

[[constraint]]
  name = "github.com/imroc/req"
  version = "0.2.3"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/now"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"

[[constraint]]
  branch = "master"
  name = "github.com/lestrrat/go-file-rotatelogs"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/qiniu/api.v7"
  version = "7.2.5"

[[constraint]]
  name = "github.com/rifflock/lfshook"
  version = "2.4.0"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.1.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "gopkg.in/gomail.v2"
  version = "2.0.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[prune]
  go-tests = true
  unused-packages = true
